language: bash

sudo: required

services:
  - docker

script:
#  - docker run -it -v $PWD:/e2e -w /e2e -e CYPRESS_RECORD_KEY=$CY_KEY cypress/included:3.4.0 --parallel --group $TESTFOLDER --ci-build-id TRAVIS_BUILD_ID
  - docker run -it -w /e2e -e CYPRESS_RECORD_KEY=$CY_KEY cypress/included:3.4.0 --parallel --group $TESTFOLDER --ci-build-id TRAVIS_BUILD_ID

env:
  - TESTFOLDER=integration/cameras/group_1/
  - TESTFOLDER=integration/cameras/group_2/
