sudo: false
language: node_js
node_js: "10"

testSmokeCy: &testSmokeCy
  script:
  - npm run cy:run:smoke -- --record --key $CY_KEY --parallel --group smoke-tests --ci-build-id TRAVIS_BUILD_ID
  - kill $(jobs -p) || true

before_install:
- sudo apt-get install libgconf-2-4
- npm install tslint

install:
- npm ci

jobs:
  fast_finish: true
  allow_failures:
  - name: "Cypress Snapshot tests"
  include:
  - stage: "Publish"
    install: true
    script:
    - npm ci
  - script:
    name: "Cypress Tests 1t thread"
    <<: *testSmokeCy
  - script:
    name: "Cypress Tests 2d thread"
    <<: *testSmokeCy
  - script:
    name: "Cypress Tests 3d thread"
    <<: *testSmokeCy
  - script:
    name: "Cypress Tests 4d thread"
    <<: *testSmokeCy

cache:
  apt: true
  npm: true
  directories:
  - node_modules
  - ~/.npm
  - ~/.cache
