sudo: required

language: python

services:
  - docker

before_install:
#  - docker build -t transpoco/cypress:1.0 .
  - docker run -it -v $PWD:/e2e -w /e2e -e CYPRESS_RECORD_KEY=bda27b52-019f-4fe1-a879-20202a07f99d transpoco/cypress:1.0