sudo: false
language: node_js
node_js: "10"

service:
  - docker

testSmokeCy: &testSmokeCy
  script:
  - docker run -it -v $PWD:/usr/src/app -e CYPRESS_RECORD_KEY=$CY_KEY transpoco/cypress -- --record --parallel --group cypress-parallel --ci-build-id TRAVIS_BUILD_ID
  - kill $(jobs -p) || true

before_install:
- docker build -t transpoco/cypress .

jobs:
  fast_finish: true
  allow_failures:
  include:
  - stage: 
    install: true
    script:
    - npm ci
  - script:
    name: "Cypress Node 1"
    <<: *testSmokeCy
  - script:
    name: "Cypress Node 2"
    <<: *testSmokeCy
  - script:
    name: "Cypress Node 3"
    <<: *testSmokeCy
  - script:
    name: "Cypress Node 4"
    <<: *testSmokeCy

cache:
  apt: true
  npm: true
  directories:
  - node_modules
  - ~/.npm
  - ~/.cache
