sudo: required

services:
  - docker

install:
  - docker run -it -v $PWD:/e2e -w /e2e -e CYPRESS_RECORD_KEY=bda27b52-019f-4fe1-a879-20202a07f99d cypress/included:3.4.0 --record --parallel

notifications: 
  email:
    recipients:
      - jehnyffen.milliam@transpoco.com
      - camille.nogueira@transpoco.com
      
    on_success: always
    on_failure: always
